import pandas as pd
try:
    url = "https://archives.nseindia.com/content/indices/ind_nifittotalmarket_list.csv"
    df = pd.read_csv(url)
    FULL_STOCKS = df['Symbol'].dropna().tolist()[:500]
except:
    FULL_STOCKS = ["RELIANCE","TCS","INFY","HDFCBANK","ICICIBANK","SBIN","BHARTIARTL","ITC","LT","KOTAKBANK","AXISBANK","BAJFINANCE","ASIANPAINT","MARUTI","HCLTECH","SUNPHARMA","TITAN","WIPRO","ULTRACEMCO","POWERGRID","360ONE","AARTIIND","AFFLE","AUBANK","BANDHANBNK","BATAINDIA","BEL","BHEL","BIOCON","BOSCHLTD","CAMS","CDSL","CGPOWER","COFORGE","DABUR","FEDERALBNK","INDHOTEL","JINDALSTEL","MUTHOOTFIN","NMDC","PEL","PERSISTENT","POLYCAB","SAIL","SIEMENS","TATAPOWER","TRENT","TVSMOTOR","ZEEL"]FULL_STOCKS = [
"ASTRAL","AUBANK","AUROPHARMA","ABFRL","BALKRISIND","BANDHANBNK","BANKBARODA","BATAINDIA",
"CANBK","CHOLAFIN","CUB","CUMMINSIND","DIXON","ESCORTS","FEDERALBNK","FORTIS",
"GODREJPROP","GUJGASLTD","HINDCOPPER","IDFCFIRSTB","INDHOTEL","INDIAMART","IEX","IGL",
"IPCALAB","JUBLFOOD","LICHSGFIN","LTF","MANAPPURAM","MCX","METROPOLIS","MFSL",
"MGL","MUTHOOTFIN","NAM-INDIA","NATIONALUM","NAUKRI","OBEROIRLTY","OFSS",
"PAGEIND","PEL","PFIZER","PHOENIXLTD","PNB","POLYCAB","PVRINOX","RAMCOCEM",
"RBLBANK","RECLTD","SBICARD","SUNTV","TATACHEM","TORNTPHARM","TRENT","TVSMOTOR",
"VOLTAS","ZEEL","AARTIIND","AAVAS","AFFLE","AJANTPHARM","AKZOINDIA","APLLTD",
"ATUL","BAJAJHLDNG","BAYERCROP","BBTC","BHARATRAS","BIRLACORPN","BLUESTARCO",
"CANFINHOME","CARBORUNDM","CASTROLIND","CEATLTD","CENTURYPLY","CERA","CHAMBLFERT",
"CHOLAHLDNG","CREDITACC","CRISIL","CROMPTON","CYIENT","DEEPAKNTR","EIDPARRY",
"ELGIEQUIP","EMAMILTD","ENDURANCE","EXIDEIND","FDC","FINCABLES","FINEORG",
"FRETAIL","GHCL","GILLETTE","GLAXO","GNFC","GODREJAGRO","GRANULES","GRAPHITE",
"GRINDWELL","GSFC","GSPL","HATHWAY","HATSUN","HEG","HEMIPROP","HFCL",
"HONAUT","HSCL","IBULHSGFIN","IDFC","IIFL","INDIACEM","INDIGOPNTS","JBCHEPHARM",
"JINDALSTEL","JKCEMENT","JKLAKSHMI","JMFINANCIL","JUSTDIAL","JYOTHYLAB",
"KAJARIACER","KANSAINER","KEI","KPRMILL","KRBL","KSB","KSCL","KTKBANK",
"LAOPALA","LAXMIMACH","LEMONTREE","LTTS","LUXIND","MAHABANK","MAHSEAMLES",
"MASTEK","MAXVIL","MAYURUNIQ","MINDACORP","MOIL","MOTILALOFS","MPHASIS",
"NATCOPHARM","NBCC","NCC","NH","NLCINDIA","NOCIL","OBEROIRLTY","OIL",
"ORIENTELEC","PCJEWELLER","PFIZER","POLYMED","POLYPLEX","PRESTIGE","PTC",
"QUESS","RADICO","RAJESHEXPO","RALLIS","RATNAMANI","RAYMOND","REDINGTON",
"RELAXO","REPCOHOME","SFL","SHOPERSTOP","SKFINDIA","SOBHA","SONATSOFTW",
"SPARC","SUDARSCHEM","SUNTECK","SUPRAJIT","SUPREMEIND","SWANENERGY","SYMPHONY",
"TTKPRESTIG","TTMT","UCOBANK","UJJIVAN","UJJIVANSFB","VGUARD","VTL",
"WELCORP","WELSPUNLTD","WHIRLPOOL","WOCKPHARMA","ZENSARTECH"
]
